name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.DIGITALOCEAN_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.DROPLET_IP}} >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" . root@${{ secrets.DROPLET_IP}}:/var/www/html
