name: Build ,DEPLOY

# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: 'Image version'
#         required: true
on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Build image 
        run: docker build -t urevise .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKENP }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run:
          docker tag urevise registry.digitalocean.com/urevise-frontend/urevise
          # docker tag urevise registry.digitalocean.com/urevise-frontend:${{github.event.inputs.version }}
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/urevise-frontend/urevise

        # run: docker push rgiegistry.ditalocean.com/urevise-frontend:${{ github.event.inputs.version }}

      - name: Deploy to DigitalOcean
        uses: do-actions/deploy@v1.1.0
        with:
           api_token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
           ssh_key: ${{ secrets.DIGITALOCEAN_SSH_PUBLIC_KEY }}
           droplet_id: ${{ secrets.DROPLET_IP }}
           script: |
            docker pull registry.digitalocean.com/urevise-frontend/urevise:latest
            docker stop urevise
            # Remove old container
            # docker rm $(echo $IMAGE_NAME)
            docker rm urevise
            # Run a new container from a new image
            docker run -d 
            --restart always \
            --name urevise