name: Build and publish manually


on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: build_and_push
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
      - name: Login to the DigitalOcean Registry
        run: |
          echo ${{ secrets.DIGITALOCEAN_API_TOKENP }} | docker login -u __token --password-stdin registry.digitalocean.com
      # - name: Copy SSH key
      #   uses: appleboy/ssh-action@v0.1.3
      #   with:
      #     name: ssh-key
      #     path: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

      # - name: Deploy to Droplet
      #   uses: appleboy/ssh-action@v0.1.3
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: root
      #     private-key: ${{ steps.copy-ssh-key.outputs.path }}

          script: |
             docker login -u ${{ secrets.DIGITALOCEAN_API_TOKENP }} -p ${{ secrets.DIGITALOCEAN_API_TOKENP }} registry.digitalocean.com/urevise-frontend
            # docker login -u root ${{ secrets.MAC_SSH_PRIVATE_KEY}} ${secrets.HOST}

            docker pull registry.digitalocean.com/urevise-frontend/urevise:latest
            docker stop urevise
            # Remove old container
            # docker rm $(echo $IMAGE_NAME)
            docker rm urevise
            # Run a new container from a new image
            docker run -d 
            --restart always \
            --name urevise
            # --name $(echo $IMAGE_NAME) \

    
