name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: 14

    # - name: Install dependencies
    #   run: rm -rf node_modules && yarn install --frozen-lockfile

    # - name: Build application
    #   run: yarn run build

    - name: Deploy to DigitalOcean
      uses: easingthemes/ssh-deploy@main
      env:
       SSH_PRIVATE_KEY: ${{ secrets.MAC_SSH_PRIVATE_KEY }}
       REMOTE_USER: ${{ secrets.USERNAME }}
       REMOTE_HOST: ${{ secrets.HOST }}
       SCRIPT: |
          cd /var/www/my-app
          ls-a
