name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.7
      with:
       key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
       host: ${{ secrets.HOST }}
       username: root
       script: |
           docker login -u ${{ secrets.DIGITALOCEAN_API_TOKENP }} -p ${{ secrets.DIGITALOCEAN_API_TOKENP }} registry.digitalocean.com/urevise-frontend
           docker pull registry.digitalocean.com/urevise-frontend/urevise:latest
           docker stop urevise
           # Remove old container
            # docker rm $(echo $IMAGE_NAME)
            docker rm urevise
            # Run a new container from a new image
            docker run -d 
            --restart always \
            --name urevise
            # --name $(echo $IMAGE_NAME) \

