name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.7
      with:
       key: ${{ secrets.MG_PC_TO_DO_PRIVATE }}
       host: ${{ secrets.HOST }}
       username: root
       script: |
           docker pull registry.digitalocean.com/urevise-frontend/urevise:latest

